from .report import ReportItem, ValidationStatus, StudentId
import datetime


class MDReport:
    _report_record: list[ReportItem]

    def __init__(self, report_record: list[ReportItem]):
        self._report_record = report_record

    # FIXME not working as expected, write unit test first!
    @staticmethod
    def _unordered_partition_array[T](l: list[T], n: int) -> list[list[T]]:
        """Divide Array Into Sub Array By A Size"""
        return [l[i::n] for i in range(n)]

    @staticmethod
    def _generate_section(title: str, id_list: list[StudentId]) -> str:
        return f"""## {title}

    {"\n".join([", ".join(row) for row in MDReport._unordered_partition_array(id_list, 9)])}
    """

    @staticmethod
    def _generate_note() -> str:
        return """## Notes

    This document generated by validate-assignments.

    See: github.com/mahdi-farnia/validate-assignments
    """

    def gen_report(self) -> str:
        run_failed_runs: list[StudentId] = [
            record[0]
            for record in self._report_record
            if record[1] == ValidationStatus.RUN_FAILED
        ]
        compilation_failed_runs: list[StudentId] = [
            record[0]
            for record in self._report_record
            if record[1] == ValidationStatus.COMPILATION_FAILED
        ]
        invalid_output_runs: list[StudentId] = [
            record[0]
            for record in self._report_record
            if record[1] == ValidationStatus.INVALID_OUTPUT
        ]
        successful_runs: list[StudentId] = [
            record[0]
            for record in self._report_record
            if record[1] == ValidationStatus.SUCCEEDED
        ]

        output: str = f"""# Result For Run {datetime.datetime.now(datetime.timezone.utc)}

    Summary:
    - Total Runs => {len(self._report_record)}
    - Successful Runs => {len(successful_runs)}
    - Failed Runs => {len(compilation_failed_runs) + len(run_failed_runs)}
        + Compilation Failed Runs => {len(compilation_failed_runs)}
        + Run Failed Runs => {len(run_failed_runs)}
        + Invalid Output Runs => {len(invalid_output_runs)}

    {self._generate_section("Successful Runs", successful_runs)}
    {self._generate_section("Compilation Failed Runs", compilation_failed_runs)}
    {self._generate_section("Run Failed Runs", run_failed_runs)}
    {self._generate_section("Invalid Output Runs", invalid_output_runs)}
    {self._generate_note()}"""

        return output
